---
# file: tasks/installation.yml
#
# installation tasks.
#

- name: installation | ensure diamond installation dependencies are present
  apt:
    name="{{ item }}"
    state=present
  with_items: "{{ diamond_dependencies }}"

- name: installation | ensure diamond is installed
  apt: name="diamond={{ diamond_version }}" state=present update_cache=true
